"""
tests/test_exporter.py
======================
Pytest tests for constants and schema definitions in exporter.py,
and end-to-end Excel file generation using tmp_path.

No network calls. All tests run in under 3 seconds.
"""

import pytest
from pathlib import Path
from exporter import DATA_FIELDS, FLAG_FIELDS, export_excel


class TestSchemaConstants:

    def test_data_fields_contains_expected_columns(self):
        expected = {"Name", "Phone", "Website", "Postcode", "Category", "Source"}
        assert expected == set(DATA_FIELDS)

    def test_data_fields_has_no_duplicates(self):
        assert len(DATA_FIELDS) == len(set(DATA_FIELDS))

    def test_flag_fields_extends_data_fields(self):
        assert FLAG_FIELDS[:len(DATA_FIELDS)] == DATA_FIELDS

    def test_flag_fields_contains_flag_reason(self):
        assert "Flag Reason" in FLAG_FIELDS

    def test_flag_fields_has_no_duplicates(self):
        assert len(FLAG_FIELDS) == len(set(FLAG_FIELDS))

    def test_flag_reason_is_last_column(self):
        assert FLAG_FIELDS[-1] == "Flag Reason"


class TestExportExcel:

    def _make_row(self):
        return {
            "Name": "ACME Ltd", "Phone": "07700900000",
            "Website": "https://acme.com", "Postcode": "SW1A 1AA",
            "Category": "Member", "Source": "Test",
        }

    def _make_stats(self):
        return {
            "Run date": "2026-05-10", "Source label": "Test",
            "Source endpoint": "https://example.com/api",
            "Total processed": 1, "Clean records": 1, "Flagged records": 0,
            "With phone": 1, "With website": 1, "Elapsed": "0m 01s",
            "Status": "COMPLETE", "Generated by": "JSON Directory Harvester",
            "Version": "1.0.0",
        }

    def test_creates_xlsx_file(self, tmp_path):
        path = tmp_path / "output.xlsx"
        export_excel([self._make_row()], [], path, self._make_stats())
        assert path.exists()

    def test_xlsx_file_is_not_empty(self, tmp_path):
        path = tmp_path / "output.xlsx"
        export_excel([self._make_row()], [], path, self._make_stats())
        assert path.stat().st_size > 0

    def test_creates_file_with_empty_clean_rows(self, tmp_path):
        path = tmp_path / "empty.xlsx"
        export_excel([], [], path, self._make_stats())
        assert path.exists()

    def test_creates_file_with_flagged_rows(self, tmp_path):
        path = tmp_path / "flagged.xlsx"
        flagged = {**self._make_row(), "Flag Reason": "Missing postcode"}
        export_excel([], [flagged], path, self._make_stats())
        assert path.exists()

    def test_output_directory_created_if_missing(self, tmp_path):
        nested = tmp_path / "new_dir" / "output.xlsx"
        export_excel([self._make_row()], [], nested, self._make_stats())
        assert nested.exists()
